# Generated by Django 4.1.7 on 2023-05-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Antártica', 'Antártica'), ('Ártico', 'Ártico'), ('Patagônia', 'Patagônia')], max_length=100)),
                ('category', models.CharField(choices=[('Paisagem', 'Paisagem'), ('Animal', 'Animal'), ('Ciência', 'Ciência')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
