# Generated by Django 4.1.7 on 2023-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_foto_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
